micronaut:
  application:
    name: rota
datasources:
  default:
    url: jdbc:h2:mem:dev;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: NONE
    dialect: H2
flyway:
  datasources:
    default:
      enabled: true 

