micronaut:
  application:
    name: rota
datasources:
  default:
    url: jdbc:h2:file:./devtest
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: NONE
    dialect: H2
flyway:
  datasources:
    default:
      enabled: true 

